name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs: 
  build:
    name: Build and test
    runs-on: self-hosted
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
    steps:
      - uses: actions/checkout@v3
          
      - name: Install sonar-scanner and build-wrapper
        run: |
          ./ci/download-sonar-scanner.ps1
      - name: Run build-wrapper
        run: |
          ./ci/set-sonar-variables.ps1
          $Location = $(Get-Location)
          & $env:SONAR_DIRECTORY/build-wrapper-win-x86/build-wrapper-win-x86-64.exe --out-dir bw-output "C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\DotNet\UnrealBuildTool\UnrealBuildTool.exe" "${Location}/UnrealPokemon.uproject" UnrealEditor Win64 DebugGame
      
      - name: Run Tests
        run: |
          ./ci/run_tests.ps1
          
      - name: Run Python Tests
        working-directory: Content/Python
        run: |
          python -m venv venv
          ./venv/Scripts/activate.ps1
          pip install -r requirements.txt
          coverage run -m unittest discover -s . -p "test_*.py"
          cd ../..
          coverage xml --omit=Content/Python/test/* coverage xml --omit=Content/Python/test/* -o python-coverage.xml Content/Python/src/**/*.py -o python-coverage.xml
          
      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./ci/set-sonar-variables.ps1
          & $env:SONAR_SCANNER_HOME/bin/sonar-scanner.bat --define sonar.cfamily.build-wrapper-output=bw-output -D sonar.host.url=https://sonarcloud.io -D sonar.cfamily.cobertura.reportPaths=cpp-coverage.xml -D sonar.python.coverage.reportPaths=python-coverage.xml -D sonar.cfamily.threads=3
          
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          path: |
            cpp-coverage.xml
            python-coverage.xml
            TestResults/*