name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs: 
  python-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Requirements
        working-directory: Content/Python
        run: pip install -r requirements.txt

      - name: Run Tests
        working-directory: Content/Python
        run: coverage run -m unittest discover -s . -p "test_*.py"

      - name: Generate Coverage Report
        run: coverage xml --omit=Content/Python/test/* -o python-coverage.xml Content/Python/src/**/*.py

      - uses: actions/upload-artifact@v3
        with:
          path: python-coverage.xml
  
  build:
    name: Build and test
    runs-on: self-hosted
    needs: python-test
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
    steps:
      - uses: actions/checkout@v3
          
      - name: Install sonar-scanner and build-wrapper
        run: |
          ./ci/download-sonar-scanner.ps1
      - name: Run build-wrapper
        run: |
          ./ci/set-sonar-variables.ps1
          $Location = $(Get-Location)
          & $env:SONAR_DIRECTORY/build-wrapper-win-x86/build-wrapper-win-x86-64.exe --out-dir bw-output "C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\DotNet\UnrealBuildTool\UnrealBuildTool.exe" "${Location}/UnrealPokemon.uproject" UnrealEditor Win64 DebugGame
      
      - name: Run Tests
        run: |
          ./ci/run_tests.ps1

      - uses: actions/download-artifact@v3
          
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          path: |
            cpp-coverage.xml
            TestResults/*
          
      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./ci/set-sonar-variables.ps1
          & $env:SONAR_SCANNER_HOME/bin/sonar-scanner.bat --define sonar.cfamily.build-wrapper-output=bw-output -D sonar.host.url=https://sonarcloud.io -D sonar.cfamily.cobertura.reportPaths=cpp-coverage.xml -D sonar.python.coverage.reportPaths=artifacts/python-coverage.xml -D sonar.cfamily.threads=2
      
  
  code-coverage:
    runs-on: ubuntu-latest
    needs: 
      - build
      - python-test
    steps:
      - uses: actions/checkout@v3
          
      - uses: actions/download-artifact@v3
          
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: artifact/*-coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'